### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by delirious-lettuce** [lgiordani/datastats#2]
I understand that the whole point of the blog post was to refactor the code (and I enjoyed the article). I guess I'm just curious about what the refactoring would look like if the initial code started like this:

```python
import json
from itertools import groupby
from statistics import mean


class DataStats:

    def stats(self, data, iage, isalary):
        # iage and isalary are the starting age and salary used to
        # compute the average yearly increase of salary.

        average_age = int(mean(e['age'] for e in data))

        # Compute the minimum, maximum and average salaries
        salaries = sorted(int(e['salary'].lstrip('£')) for e in data)
        average_salary = int(mean(salaries))

        salary_groups = [list(g) for _, g in groupby(salaries)]
        min_salary = salary_groups[0]
        max_salary = salary_groups[-1]

        # Compute average yearly increase
        average_age_increase = average_age - iage
        average_salary_increase = average_salary - isalary

        yearly_avg_increase = average_salary_increase // average_age_increase

        return json.dumps({
            'avg_age': average_age,
            'avg_salary': average_salary,
            'avg_yearly_increase': yearly_avg_increase,
            'max_salary': max_salary,
            'min_salary': min_salary
        })

```

The tags on your post seem to indicate that you are using Python 3. That allows using `statistics.mean` instead of rolling separate "avg" functions.

While your final version may be easier to test than your original, it seems like there is repeated work and unnecessary functions which over-complicate the solution.

**Comment by lgiordani** [comment]
You are right. The example in the article is purposely reinventing the wheel to give a simple context where to explore a complex matter such as refactoring. In the case that you present I probably wouldn't really refactor the method if the code inside `stats()` wasn't used by other functions. After all, one of the main purpose of refactoring is to remove code duplication.

The only thing I would question is the necessity of a class to host a self-contained method, and probably I would extract that. This would however change the API, so other considerations shall be done.

Does this make sense?

**Comment by delirious-lettuce** [comment]
Yes, that makes perfect sense. Thanks for taking the time to respond!

**Comment by lgiordani** [comment]
Thank you for taking the time to read, review and comment my work!
