### ISSUE TITLE
One more code duplication

### ISSUE THREAD

**Issue by harunyasar** [lgiordani/datastats#3]
Hi. I have stumbled upon your awesome Test-Driven Refactoring blog post :) It is very helpful and explanatory. I'm not gonna debate and I'm not sure whether it is necessary.

https://github.com/lgiordani/datastats/blob/develop/datastats/datastats.py#L29-L33

Those two functions share the same logic. If I were you, I would parametrize this common logic like this:

```python
def _calculate_avg(self, sum_of_numbers):
    return math.floor(sum_of_numbers / len(self.data))

def _avg_salary(self):
    return self._calculate_avg(sum(self._salaries))

def _avg_age(self):
    return self._calculate_avg(sum(self._ages))
```

Edit... Even you could call this average calculation function directly:

```python
return {
    'avg_age': self._calculate_avg(self._ages),
    'avg_salary': self._calculate_avg(self._salaries),
    'avg_yearly_increase': self._avg_yearly_increase(iage, isalary),
    'max_salary': self._max_salary(),
    'min_salary': self._min_salary()
}
```

But I would prefer to use this approach:

```python
return {
    'avg_age': self._avg_salary(),
    'avg_salary': self._avg_age(),
    'avg_yearly_increase': self._avg_yearly_increase(iage, isalary),
    'max_salary': self._max_salary(),
    'min_salary': self._min_salary()
}
```
Because the person who reads this code could understand what is going on at first glance. Therefore, the sum of the numbers will not need to be passed to this new function.

Many thanks!

**Comment by lgiordani** [comment]
@harunyasar sorry for not answering before, I read the message and then completely forgot to reply... :see_no_evil: I agree with your correction, well spotted! The second approach is the one I like as well, for the reason that you mentioned. I will fix code and post today and close this when it's done. Thanks!

**Comment by lgiordani** [comment]
I just updated both the repository and the post on the blog. Thanks a lot, well done!
